[workspace]
name = "learning_c"
version = "0.1.0"
description = "A small repo for learning C with Pixi"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
gcc = "*"
gdb = "*"
bash = "*"

[tasks.build]
cmd = "mkdir -p build/{{ target }} && gcc -Wall -Wextra -std=c11 -g -nodefaultrpaths src/{{ target }}/main.c -o build/{{ target }}/main"
args = ["target"]

[tasks.exec]
cmd = "bash scripts/resolve_and_run.sh {{ target }}"
args = ["target"]

[tasks.debug]
cmd = "bash scripts/resolve_and_debug.sh {{ target }}"
args = ["target"]

[tasks.clean]
cmd = "rm -rf build"
